############## style ##############
style:
  layout:
    max-width: "1125px" #最大宽度
  color:
    theme-main: "#ad9551" # 主色调
    theme-secondary: "#DDF0FF" # 次色调
    text-main: "#333333" # 文字主色调
    text-secondary: "#898FA0" # 文字次色调


########## About Homepage Settings ##########
# icon
icon:  /favicon.ico #Favicon place in source
#  header
site_name: ROSAI

menu:
  HOME: /
  DESIGN: /design
  WEB DEV: /webdev
  SEO: /seo
  PRODUCTS: /products
  BLOG: /archives

##Local Search

search:
  open: true # to enable search
  page: /search # Search

intro:
  title: we are ROSAI.
  sub: 'A web services company'
  avator:
  author: ROSAI

#Contact Information
#Icons：https://remixicon.com/
contact:
  Github:
    - https://github.com/rosaiservices
    - ri-github-line
  Email:
    - mailto:contact@rosai.co.uk
    - ri-mail-line
  Tunnel:
    - https://tunnel.rosai.co.uk
    - ri-cloud-line

########## 关于文章的设置 ##########

# 文章toc索引栏设置
toc:
  max: 2 #最大
  min: 2 #最小

# 插件
plugins:
  # 代码高亮，想要使用代码高亮，得先把根目录的_config.yml里的highlight的enable置成false
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/github.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles

# 评论系统设置
comments:
  valine:
    open: false # true | false 是否打开
    appid: #Leancloud应用的AppID  这里和下面的要换成你自己的啊QAQ
    appkey: #Leancloud应用的AppKey
    verify: false #验证码
    notify: true #评论回复提醒
    avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
    #头像类型可见： https://valine.js.org/avatar.html
    placeholder: 留下你来过的痕迹~ #评论框占位符
  gitalk:
    open: false # true | false 是否打开
    owner:  #Github 用户名,
    repo:  #储存评论issue的github仓库名
    admin:  #Github 用户名
    clientID:  #`Github Application clientID`
    clientSecret: #`Github Application clientSecret`




# Theme footer
footer: Powered by [Hexo](http://hexo.io/). Theme by [Chalk](https://github.com/isEmmanuelOlowe/hexo-theme-chalk).
